/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProceduresRouteImport } from './routes/procedures'
import { Route as PolicyUploadRouteImport } from './routes/policy-upload'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as HospitalUsersRouteImport } from './routes/hospital-users'
import { Route as HospitalConfigRouteImport } from './routes/hospital-config'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DiseasesRouteImport } from './routes/diseases'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresRoute = ProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyUploadRoute = PolicyUploadRouteImport.update({
  id: '/policy-upload',
  path: '/policy-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalUsersRoute = HospitalUsersRouteImport.update({
  id: '/hospital-users',
  path: '/hospital-users',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalConfigRoute = HospitalConfigRouteImport.update({
  id: '/hospital-config',
  path: '/hospital-config',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasesRoute = DiseasesRouteImport.update({
  id: '/diseases',
  path: '/diseases',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/claims': typeof ClaimsRoute
  '/dashboard': typeof DashboardRoute
  '/diseases': typeof DiseasesRoute
  '/history': typeof HistoryRoute
  '/hospital-config': typeof HospitalConfigRoute
  '/hospital-users': typeof HospitalUsersRoute
  '/hospitals': typeof HospitalsRoute
  '/policies': typeof PoliciesRoute
  '/policy-upload': typeof PolicyUploadRoute
  '/procedures': typeof ProceduresRoute
  '/reset-password': typeof ResetPasswordRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/claims': typeof ClaimsRoute
  '/dashboard': typeof DashboardRoute
  '/diseases': typeof DiseasesRoute
  '/history': typeof HistoryRoute
  '/hospital-config': typeof HospitalConfigRoute
  '/hospital-users': typeof HospitalUsersRoute
  '/hospitals': typeof HospitalsRoute
  '/policies': typeof PoliciesRoute
  '/policy-upload': typeof PolicyUploadRoute
  '/procedures': typeof ProceduresRoute
  '/reset-password': typeof ResetPasswordRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/claims': typeof ClaimsRoute
  '/dashboard': typeof DashboardRoute
  '/diseases': typeof DiseasesRoute
  '/history': typeof HistoryRoute
  '/hospital-config': typeof HospitalConfigRoute
  '/hospital-users': typeof HospitalUsersRoute
  '/hospitals': typeof HospitalsRoute
  '/policies': typeof PoliciesRoute
  '/policy-upload': typeof PolicyUploadRoute
  '/procedures': typeof ProceduresRoute
  '/reset-password': typeof ResetPasswordRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/claims'
    | '/dashboard'
    | '/diseases'
    | '/history'
    | '/hospital-config'
    | '/hospital-users'
    | '/hospitals'
    | '/policies'
    | '/policy-upload'
    | '/procedures'
    | '/reset-password'
    | '/result'
    | '/settings'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/claims'
    | '/dashboard'
    | '/diseases'
    | '/history'
    | '/hospital-config'
    | '/hospital-users'
    | '/hospitals'
    | '/policies'
    | '/policy-upload'
    | '/procedures'
    | '/reset-password'
    | '/result'
    | '/settings'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/claims'
    | '/dashboard'
    | '/diseases'
    | '/history'
    | '/hospital-config'
    | '/hospital-users'
    | '/hospitals'
    | '/policies'
    | '/policy-upload'
    | '/procedures'
    | '/reset-password'
    | '/result'
    | '/settings'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  ClaimsRoute: typeof ClaimsRoute
  DashboardRoute: typeof DashboardRoute
  DiseasesRoute: typeof DiseasesRoute
  HistoryRoute: typeof HistoryRoute
  HospitalConfigRoute: typeof HospitalConfigRoute
  HospitalUsersRoute: typeof HospitalUsersRoute
  HospitalsRoute: typeof HospitalsRoute
  PoliciesRoute: typeof PoliciesRoute
  PolicyUploadRoute: typeof PolicyUploadRoute
  ProceduresRoute: typeof ProceduresRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultRoute: typeof ResultRoute
  SettingsRoute: typeof SettingsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures': {
      id: '/procedures'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof ProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-upload': {
      id: '/policy-upload'
      path: '/policy-upload'
      fullPath: '/policy-upload'
      preLoaderRoute: typeof PolicyUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-users': {
      id: '/hospital-users'
      path: '/hospital-users'
      fullPath: '/hospital-users'
      preLoaderRoute: typeof HospitalUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-config': {
      id: '/hospital-config'
      path: '/hospital-config'
      fullPath: '/hospital-config'
      preLoaderRoute: typeof HospitalConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseases': {
      id: '/diseases'
      path: '/diseases'
      fullPath: '/diseases'
      preLoaderRoute: typeof DiseasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  ClaimsRoute: ClaimsRoute,
  DashboardRoute: DashboardRoute,
  DiseasesRoute: DiseasesRoute,
  HistoryRoute: HistoryRoute,
  HospitalConfigRoute: HospitalConfigRoute,
  HospitalUsersRoute: HospitalUsersRoute,
  HospitalsRoute: HospitalsRoute,
  PoliciesRoute: PoliciesRoute,
  PolicyUploadRoute: PolicyUploadRoute,
  ProceduresRoute: ProceduresRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultRoute: ResultRoute,
  SettingsRoute: SettingsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
